Conda uses environments to load different sets of Python packages
type conda env list to see the environments availible.
Global seed set to 42
Traceback (most recent call last):
  File "../main.py", line 91, in <module>
    main()
  File "../main.py", line 84, in main
    trainer.initialize(training_bool=True)
  File "/shared/tale2/Shared/schobs/landmark_unet/ensemble/model_trainer.py", line 120, in initialize
    self.set_training_dataloaders()
  File "/shared/tale2/Shared/schobs/landmark_unet/ensemble/model_trainer.py", line 444, in set_training_dataloaders
    data_augmentation =self.model_config.DATASET.DATA_AUG
  File "/shared/tale2/Shared/schobs/landmark_unet/ensemble/dataset.py", line 108, in __init__
    datalist = load_aspire_datalist(os.path.join(self.annotation_path, label_std), data_list_key=self.split, base_dir=self.root_path)
  File "/shared/tale2/Shared/schobs/landmark_unet/ensemble/load_data.py", line 61, in load_aspire_datalist
    raise ValueError(f"data list file {data_list_file_path} does not exist.")
ValueError: data list file /shared/tale2/Shared/data/CMRI/ASPIRE/cardiac4ch_labels_VPnC_CV/fold1_12std.json does not exist.
